### ISSUE TITLE
Just a quick question about refreshing threads

### ISSUE THREAD

**Issue by bearachute** [lauritzsh/fourchan-kit#1]
I would like to incorporate this into an irc bot that pulls a thread every x amount of time. How would I go about doing this? I've tried several method and its always the same thread, also I have a /co/ bot on twitter and would love to use this since the solution I have now is less than optimal. Any insights?

**Comment by lauritzsh** [comment]
Hi, thanks for taking an interest in the project. I'm not sure if I understand, but is it the [lurk](http://lauritzsh.github.io/fourchan-kit/Fourchan/Kit/Tools.html#lurk-class_method) feature you're looking for?

You can specify a refresh rate with that and it will check the thread every x seconds to see if new images should be there. It can either be done programmatically or using the CLI.

**Comment by bearachute** [comment]
Thanks for taking the time to answer, maybe it is the lurk feature I'm looking for, but I'm not looking for the images per say just like the link to the thread who wrote it and the "com", thanks again!

**Comment by lauritzsh** [comment]
I'm sorry but I'm not sure if I follow. You want to lurk a thread for new posts and be notified of that? So whenever it check for new posts, you want a message "3 new posts found since last check!" or something like that but without downloading any images?

**Comment by bearachute** [comment]
Something like that but only really the first new post, so I'm not spamming up the channel, (it's a comic related channel) for my twitter bot probably posting like x new threads and the content would be good. It's hard to explain I guess, since I've never myself worked with APIs

**Comment by lauritzsh** [comment]
It sounds like you need lurk but unfortunately it's only for images.

I checked the documentation, maybe you could use [this](http://lauritzsh.github.io/fourchan-kit/Fourchan/Kit/Thread.html#fetch_replies-instance_method). You could fetch all replies for a thread, then every x seconds you could fetch again and count # of replies before and after. If there is one or more new replies, you could just get the newest replies and do whatever you want with those.

Does that make sense? You would have to write your own "check every x seconds" and then use that method for fetching new posts for a thread.
